"""Useful workflows and the verified technical data flow, English and Greek."""
WORKFLOWS = [
    {'slug': 'word-dictation',
     'en': {'title': 'Free Greek and English Dictation in Word on Windows',
            'description': 'Use FU Flow to dictate Greek and English text into Word on Windows. Set the microphone, use the hotkey and fix names with a local dictionary.',
            'lead': 'FU Flow can insert dictated text into a Word document through the normal Windows paste workflow. You do not need a Word add-in for this workflow.',
            'blocks': [
                ('h2', 'Start with a short document'),
                ('ol', ['Install the FU Flow Windows beta and open Settings. Select the microphone you actually use and keep the local speech engine.',
                        'Choose Greek or English as the dictation language. This setting is separate from the interface language.',
                        'Open Word, create a document and click inside the editable page. Confirm you can type there.',
                        'Press right Alt once to listen. Speak one or two sentences, then press right Alt again to insert the text.',
                        'Review names, punctuation and numbers before saving or sharing the document.']),
                ('h2', 'Greek text with English names'),
                ('p', 'For a mostly Greek paragraph, begin with Greek selected. English product names may still need correction. Put recurring mistakes into Dictionary as a spoken form and the spelling you want. For a full English paragraph, select English and test a short phrase.'),
                ('h2', 'When the text does not appear'),
                ('p', 'Check that the document is editable and the cursor is inside the text. Copy the transcript from FU Flow History and paste it manually. A protected or read-only document will not accept text. Keyboard conflicts and differences in application privileges can also affect insertion.'),
                ('h2', 'Offline recognition and document storage'),
                ('p', 'The local speech engine works offline after installation. That does not change how Word stores or syncs a document. A cloud document or another connected destination can upload the text after you insert it.'),
                ('h2', 'What this workflow does not do'),
                ('p', 'FU Flow supplies text. It does not promise to control all Word menus, formatting commands or document layout by voice. Start with dictation and edit the document using the controls you already use.') ]},
     'el': {'title': 'Δωρεάν υπαγόρευση κειμένου στο Word στα ελληνικά',
            'description': 'Γράψτε στο Word με τη φωνή σας στα ελληνικά και αγγλικά. Ρυθμίστε το FU Flow για Windows, το μικρόφωνο, το πλήκτρο και το προσωπικό λεξικό.',
            'lead': 'Το FU Flow εισάγει το υπαγορευμένο κείμενο στο Word μέσω της κανονικής επικόλλησης των Windows. Δεν χρειάζεται πρόσθετο του Word για αυτή τη χρήση.',
            'blocks': [
                ('h2', 'Ξεκινήστε με ένα μικρό έγγραφο'),
                ('ol', ['Εγκαταστήστε την έκδοση beta του FU Flow για Windows και ανοίξτε τις Ρυθμίσεις. Επιλέξτε το μικρόφωνό σας και κρατήστε την τοπική μηχανή ομιλίας.',
                        'Επιλέξτε ελληνικά ή αγγλικά ως γλώσσα υπαγόρευσης. Η επιλογή αυτή είναι ξεχωριστή από τη γλώσσα του περιβάλλοντος.',
                        'Ανοίξτε το Word, δημιουργήστε έγγραφο και πατήστε μέσα στη σελίδα. Βεβαιωθείτε ότι μπορείτε να γράψετε εκεί.',
                        'Πατήστε μία φορά το δεξί Alt. Πείτε μία ή δύο προτάσεις και πατήστε ξανά το δεξί Alt για την εισαγωγή.',
                        'Ελέγξτε ονόματα, στίξη και αριθμούς πριν αποθηκεύσετε ή μοιραστείτε το έγγραφο.']),
                ('h2', 'Ελληνικά με αγγλικά ονόματα'),
                ('p', 'Για παράγραφο κυρίως στα ελληνικά, ξεκινήστε με επιλεγμένα τα ελληνικά. Τα αγγλικά ονόματα προϊόντων μπορεί να χρειάζονται διόρθωση. Προσθέστε τα επαναλαμβανόμενα λάθη στο Λεξικό, με την προφορική μορφή και τη γραφή που θέλετε. Για ολόκληρη αγγλική παράγραφο, επιλέξτε αγγλικά και δοκιμάστε μία μικρή φράση.'),
                ('h2', 'Αν δεν εμφανιστεί το κείμενο'),
                ('p', 'Ελέγξτε ότι το έγγραφο επιτρέπει επεξεργασία και ο κέρσορας βρίσκεται μέσα στο κείμενο. Αντιγράψτε τη μεταγραφή από το Ιστορικό του FU Flow και επικολλήστε τη χειροκίνητα. Ένα προστατευμένο έγγραφο ή έγγραφο μόνο για ανάγνωση δεν δέχεται κείμενο. Συγκρούσεις πλήκτρων και διαφορετικά δικαιώματα εφαρμογών μπορούν επίσης να επηρεάσουν την εισαγωγή.'),
                ('h2', 'Τοπική αναγνώριση και αποθήκευση εγγράφων'),
                ('p', 'Η τοπική μηχανή ομιλίας λειτουργεί χωρίς σύνδεση μετά την εγκατάσταση. Αυτό δεν αλλάζει τον τρόπο που το Word αποθηκεύει ή συγχρονίζει ένα έγγραφο. Ένα έγγραφο στο σύννεφο μπορεί να στείλει το κείμενο online μετά την εισαγωγή του.'),
                ('h2', 'Τι δεν κάνει αυτή η χρήση'),
                ('p', 'Το FU Flow προσθέτει κείμενο. Δεν υπόσχεται φωνητικό χειρισμό όλων των μενού, των εντολών μορφοποίησης ή της διάταξης στο Word. Ξεκινήστε με την υπαγόρευση και επεξεργαστείτε το έγγραφο με τα εργαλεία που ήδη χρησιμοποιείτε.') ]}},
    {'slug': 'ai-prompts',
     'en': {'title': 'Voice Typing for ChatGPT and Claude on Windows',
            'description': 'Dictate AI prompts with FU Flow on Windows. Turn a spoken brief into editable text, review it and send it to ChatGPT or Claude yourself.',
            'lead': 'Use local dictation to write a fuller prompt without typing every sentence. FU Flow prepares text in the input box; you decide when to send it.',
            'blocks': [
                ('h2', 'A simple prompt workflow'),
                ('ol', ['Open the AI service you use and click in its message field.', 'Press right Alt in FU Flow and describe the task, audience, constraints and desired output.', 'Press right Alt again. Read the transcript and fix names, numbers and technical terms.', 'Send the prompt using the service controls after you have reviewed it.']),
                ('h2', 'An example brief for an automation'),
                ('p', 'Describe a process you already understand: when a new support request arrives, identify its category, draft a reply and leave the draft for a person to approve. Name the inputs and the exact result you want. Separating the trigger, action and review step makes a spoken brief easier to check.'),
                ('h2', 'Keep repeated terms consistent'),
                ('p', 'Use Dictionary for client names and technical terms that are repeatedly misheard. Use Snippets for short spoken phrases that expand into recurring instructions. Review the expansion before submitting a prompt.'),
                ('h2', 'The privacy boundary'),
                ('p', 'The default local engine does not upload speech to transcribe it. ChatGPT, Claude or any other destination receives the text you submit and handles it under its own settings and terms. Local dictation does not make a cloud AI conversation offline.'),
                ('h2', 'If insertion fails'),
                ('p', 'A message field can change focus or become temporarily disabled. Copy the transcript from History and paste it manually into the active field. FU Flow is a Windows beta, so test your browser and everyday applications before depending on automatic insertion.') ]},
     'el': {'title': 'Φωνητική πληκτρολόγηση για ChatGPT και Claude στα Windows',
            'description': 'Υπαγορεύστε εντολές για ChatGPT και Claude με το FU Flow. Τοπική μετατροπή ομιλίας σε κείμενο, έλεγχος και αποστολή από εσάς.',
            'lead': 'Χρησιμοποιήστε τοπική υπαγόρευση για να γράψετε πληρέστερες εντολές χωρίς να πληκτρολογείτε κάθε πρόταση. Το FU Flow ετοιμάζει το κείμενο και εσείς αποφασίζετε πότε θα το στείλετε.',
            'blocks': [
                ('h2', 'Μια απλή διαδικασία'),
                ('ol', ['Ανοίξτε την υπηρεσία AI που χρησιμοποιείτε και πατήστε στο πεδίο μηνύματος.', 'Πατήστε δεξί Alt στο FU Flow και περιγράψτε τη δουλειά, το κοινό, τους περιορισμούς και τη μορφή του αποτελέσματος.', 'Πατήστε ξανά δεξί Alt. Διαβάστε τη μεταγραφή και διορθώστε ονόματα, αριθμούς και τεχνικούς όρους.', 'Στείλτε το μήνυμα από τα χειριστήρια της υπηρεσίας αφού το ελέγξετε.']),
                ('h2', 'Παράδειγμα περιγραφής ενός αυτοματισμού'),
                ('p', 'Περιγράψτε μια διαδικασία που ήδη γνωρίζετε: όταν έρχεται αίτημα υποστήριξης, να αναγνωρίζεται η κατηγορία, να ετοιμάζεται μια απάντηση και να μένει για ανθρώπινη έγκριση. Ορίστε τα δεδομένα εισόδου και το αποτέλεσμα. Ο διαχωρισμός του γεγονότος εκκίνησης, της ενέργειας και του ελέγχου κάνει την προφορική περιγραφή πιο εύκολη στην αξιολόγηση.'),
                ('h2', 'Σταθεροί όροι σε κάθε εντολή'),
                ('p', 'Χρησιμοποιήστε το Λεξικό για ονόματα πελατών και τεχνικούς όρους που αναγνωρίζονται λάθος. Με τα Αποσπάσματα, σύντομες προφορικές φράσεις μπορούν να ανοίγουν σε οδηγίες που επαναλαμβάνετε. Ελέγξτε το τελικό κείμενο πριν το υποβάλετε.'),
                ('h2', 'Πού σταματά η τοπική ιδιωτικότητα'),
                ('p', 'Η προεπιλεγμένη τοπική μηχανή δεν ανεβάζει την ομιλία για μεταγραφή. Το ChatGPT, το Claude ή η άλλη υπηρεσία λαμβάνει το κείμενο που υποβάλλετε και το διαχειρίζεται σύμφωνα με τις δικές της ρυθμίσεις και όρους. Η τοπική υπαγόρευση δεν μετατρέπει μια συνομιλία με υπηρεσία στο σύννεφο σε offline χρήση.'),
                ('h2', 'Αν αποτύχει η εισαγωγή'),
                ('p', 'Ένα πεδίο μηνύματος μπορεί να χάσει την εστίαση ή να απενεργοποιηθεί προσωρινά. Αντιγράψτε τη μεταγραφή από το Ιστορικό και επικολλήστε τη στο ενεργό πεδίο. Το FU Flow είναι beta για Windows. Δοκιμάστε τον browser και τις καθημερινές εφαρμογές σας πριν βασιστείτε στην αυτόματη εισαγωγή.') ]}},
]

PRIVACY = {
 'en': {'title': 'Local Dictation Privacy and Offline Operation',
        'description': 'How FU Flow handles speech, local history, clipboard insertion, update checks and the optional remote speech provider. Know what stays on your PC.',
        'lead': 'The default speech engine runs on your computer. This technical explanation distinguishes local recognition from updates and optional online services.',
        'blocks': [
            ('h2', 'Local speech is the default'),
            ('p', 'FU Flow ships Whisper models and runs recognition through whisper.cpp on the same PC. No FU Flow account or paid API key is required for that mode. Once installed, local dictation can work without an internet connection.'),
            ('h2', 'An optional remote provider changes the data flow'),
            ('p', 'Settings also offers an OpenAI-compatible speech provider. When you choose it, the app sends recorded audio to the endpoint you configured. The provider may require credentials and charge for processing. Its privacy and retention terms apply. Keep the local provider selected if you want speech recognition to stay on your PC.'),
            ('h2', 'Update checks use the network'),
            ('p', 'The app checks for a newer release after startup. Checking does not download an installer. If you choose an update, the app downloads it. These requests are distinct from speech transcription. The site and download host receive normal request metadata when your computer connects to them.'),
            ('h2', 'History and the destination app'),
            ('p', 'Transcripts, dictionary rules and statistics are stored locally in the app database. Text is inserted through the Windows clipboard and paste workflow. Anyone with access to your local files or clipboard may be able to read it. The program receiving the text can store or sync it under its own settings.'),
            ('h2', 'Problem and idea reports'),
            ('p', 'From version 0.9.13 the menu has a "problem or idea?" line. A report leaves the PC only when you press Send. It carries your message, the reply address if you typed one, the app version, the operating system and the interface language. The diagnostic log goes with it only while its box is ticked, and you can read the log before sending. It holds app events and errors, with the account name removed from file paths. Your dictated words are never in it. Reports go to the fuckyouflow.app server, which mails them to the maker. The server deletes its copy after 90 days. The copy sent by email stays in the inbox of the maker. The server counts reports per network address in memory to stop abuse and never stores the address.'),
            ('h2', 'Sharing Dictionary corrections'),
            ('p', 'From version 0.9.14 the app shares the corrections in your Dictionary with the maker, and it does so from the start. The app is free, and these corrections are what it asks back. The switch is in Settings under Privacy and you can turn it off at any time. While it is on, the app sends each correction to our server at fuckyouflow.app: the wrong word, the right word, its language and how it matches, together with the app version, your dictation language and a random number that stands for your install. New corrections follow about once a day. That list can include names you have put in the Dictionary. Dictated text, History and audio stay on your PC, and so do the corrections of a downloaded ready-made dictionary. On the server the corrections sit in a closed folder. A person reads them, and the ones useful to everyone go into the ready-made dictionary for that language. The switch and a "Delete what I sent" button are in Settings under Privacy. The button removes your file from the server, and the server keeps the file until you press it.'),
            ('h2', 'Ready-made dictionaries'),
            ('p', 'From version 0.9.14 the app can download a ready-made dictionary for your language: words the speech engine often mishears, checked by hand. It asks first, once, and the Dictionary page has the same button. To know whether it has something to offer, the app reads the short list of available languages from GitHub once each time it starts, until the question is answered; on the Dictionary page it reads that list only when you press the button. After a yes the app downloads the list from the public GitHub repository of FU Flow and looks for a newer version about once a day. GitHub receives normal request metadata when your computer connects to it. Only the list comes down; nothing of yours goes up with it. Every file carries the signature of the maker and the app checks it before it uses a single word. A correction you changed or deleted stays the way you left it. The Dictionary page can take the list out again.'),
            ('h2', 'Practical checks'),
            ('ul', ['Confirm the local provider in Settings before dictating sensitive material.', 'Use a short offline test to check the setup on your own PC.', 'Review what is saved in History and what you copy into another service.', 'If you report a bug, review the diagnostic text before sharing it.']),
            ('h2', 'Inspectable source'),
            ('p', 'FU Flow is MIT licensed. The public source includes the provider selection, local and remote speech adapters and the update check. This page describes application behavior as the maker documents it. An independent security audit or a compliance certification has yet to be done.') ]},
 'el': {'title': 'Ιδιωτικότητα και υπαγόρευση χωρίς ίντερνετ',
        'description': 'Πώς το FU Flow χειρίζεται ομιλία, τοπικό ιστορικό, πρόχειρο, ενημερώσεις και προαιρετικό απομακρυσμένο πάροχο. Δείτε τι μένει στον υπολογιστή σας.',
        'lead': 'Η προεπιλεγμένη μηχανή ομιλίας τρέχει στον υπολογιστή σας. Η τεχνική αυτή περιγραφή ξεχωρίζει την τοπική αναγνώριση από ενημερώσεις και προαιρετικές online υπηρεσίες.',
        'blocks': [
            ('h2', 'Η ομιλία επεξεργάζεται τοπικά από προεπιλογή'),
            ('p', 'Το FU Flow περιλαμβάνει μοντέλα Whisper και εκτελεί την αναγνώριση μέσω whisper.cpp στον ίδιο υπολογιστή. Για αυτή τη λειτουργία δεν χρειάζεται λογαριασμός FU Flow ή πληρωμένο κλειδί API. Μετά την εγκατάσταση η τοπική υπαγόρευση λειτουργεί χωρίς σύνδεση στο ίντερνετ.'),
            ('h2', 'Ο προαιρετικός απομακρυσμένος πάροχος αλλάζει τη ροή'),
            ('p', 'Οι Ρυθμίσεις προσφέρουν και πάροχο ομιλίας συμβατό με OpenAI. Αν τον επιλέξετε, η εφαρμογή στέλνει τον ηχογραφημένο ήχο στη διεύθυνση που έχετε ορίσει. Ο πάροχος μπορεί να ζητά στοιχεία σύνδεσης και να χρεώνει την επεξεργασία. Ισχύουν οι δικοί του όροι ιδιωτικότητας και διατήρησης. Κρατήστε την τοπική επιλογή αν θέλετε η αναγνώριση να μένει στον υπολογιστή σας.'),
            ('h2', 'Ο έλεγχος ενημερώσεων χρησιμοποιεί το δίκτυο'),
            ('p', 'Μετά την εκκίνηση η εφαρμογή ελέγχει αν υπάρχει νεότερη έκδοση. Ο έλεγχος δεν κατεβάζει εγκαταστάτη. Αν επιλέξετε ενημέρωση, γίνεται λήψη της. Αυτά τα αιτήματα είναι ξεχωριστά από τη μεταγραφή ομιλίας. Το site και ο πάροχος λήψης λαμβάνουν τα συνήθη στοιχεία ενός αιτήματος όταν συνδέεται ο υπολογιστής σας.'),
            ('h2', 'Ιστορικό και εφαρμογή προορισμού'),
            ('p', 'Οι μεταγραφές, οι κανόνες λεξικού και τα στατιστικά αποθηκεύονται τοπικά στη βάση της εφαρμογής. Το κείμενο εισάγεται μέσω του προχείρου και της επικόλλησης των Windows. Όποιος έχει πρόσβαση στα τοπικά αρχεία ή στο πρόχειρο μπορεί ενδεχομένως να το διαβάσει. Η εφαρμογή που λαμβάνει το κείμενο μπορεί να το αποθηκεύει ή να το συγχρονίζει σύμφωνα με τις ρυθμίσεις της.'),
            ('h2', 'Αναφορές προβλημάτων και ιδεών'),
            ('p', 'Από την έκδοση 0.9.13 το μενού έχει τη γραμμή «πρόβλημα ή ιδέα;». Μια αναφορά φεύγει από τον υπολογιστή μόνο όταν πατήσετε Αποστολή. Περιέχει το μήνυμά σας, τη διεύθυνση email αν τη γράψατε, την έκδοση της εφαρμογής, το λειτουργικό σύστημα και τη γλώσσα της εφαρμογής. Το αρχείο διάγνωσης πηγαίνει μαζί μόνο όσο είναι τσεκαρισμένο το κουτάκι του. Μπορείτε να το διαβάσετε πριν την αποστολή. Περιέχει συμβάντα και σφάλματα της εφαρμογής, με το όνομα του λογαριασμού αφαιρεμένο από τις διαδρομές αρχείων. Όσα υπαγορεύετε δεν μπαίνουν ποτέ. Οι αναφορές πηγαίνουν στον server του fuckyouflow.app, που τις στέλνει με email στον δημιουργό. Ο server σβήνει το δικό του αντίγραφο μετά από 90 μέρες. Το αντίγραφο που στάλθηκε με email μένει στο γραμματοκιβώτιο του δημιουργού. Ο server μετράει τις αναφορές ανά διεύθυνση δικτύου μόνο στη μνήμη του, για να σταματά την κατάχρηση. Τη διεύθυνση δεν την αποθηκεύει ποτέ.'),
            ('h2', 'Μοίρασμα διορθώσεων του Λεξικού'),
            ('p', 'Από την έκδοση 0.9.14 η εφαρμογή μοιράζεται με τον δημιουργό τις διορθώσεις του Λεξικού σας από την πρώτη στιγμή. Η εφαρμογή είναι δωρεάν και αυτές οι διορθώσεις είναι ό,τι ζητά ως αντάλλαγμα. Ο διακόπτης βρίσκεται στο Απόρρητο των Ρυθμίσεων και τον κλείνετε όποτε θέλετε. Όσο είναι ανοιχτός, η εφαρμογή στέλνει κάθε διόρθωση στον server μας στο fuckyouflow.app: τη λάθος λέξη, τη σωστή λέξη, τη γλώσσα της και τον τρόπο αντιστοίχισης, μαζί με την έκδοση της εφαρμογής, τη γλώσσα υπαγόρευσης και έναν τυχαίο αριθμό που αντιπροσωπεύει την εγκατάστασή σας. Οι νέες διορθώσεις ακολουθούν περίπου μία φορά την ημέρα. Η λίστα μπορεί να περιέχει ονόματα που έχετε βάλει στο Λεξικό. Τα κείμενα που υπαγορεύετε, το Ιστορικό και ο ήχος μένουν στον υπολογιστή σας, όπως και οι διορθώσεις ενός έτοιμου λεξικού που κατεβάσατε. Στον server οι διορθώσεις μένουν σε κλειστό φάκελο. Τις διαβάζει άνθρωπος και όσες χρησιμεύουν σε όλους μπαίνουν στο έτοιμο λεξικό της γλώσσας τους. Ο διακόπτης και το κουμπί «Σβήσε όσα έστειλα» βρίσκονται στις Ρυθμίσεις, στο Απόρρητο. Το κουμπί αφαιρεί το αρχείο σας από τον server, ο οποίος το κρατά μέχρι να το πατήσετε.'),
            ('h2', 'Έτοιμα λεξικά'),
            ('p', 'Από την έκδοση 0.9.14 η εφαρμογή μπορεί να κατεβάσει έτοιμο λεξικό για τη γλώσσα σας: λέξεις που η μηχανή ομιλίας συχνά ακούει λάθος, ελεγμένες από άνθρωπο. Ρωτάει πρώτα, μία φορά. Η σελίδα Λεξικό έχει το ίδιο κουμπί. Για να ξέρει αν έχει κάτι να προτείνει, η εφαρμογή διαβάζει από το GitHub τη σύντομη λίστα με τις διαθέσιμες γλώσσες μία φορά σε κάθε εκκίνηση, ώσπου να απαντηθεί η ερώτηση. Στη σελίδα Λεξικό τη διαβάζει μόνο όταν πατήσετε το κουμπί. Μετά από ένα ναι η εφαρμογή κατεβάζει τη λίστα από το δημόσιο αποθετήριο του FU Flow στο GitHub και ελέγχει για νεότερη έκδοση περίπου μία φορά την ημέρα. Το GitHub λαμβάνει τα συνήθη στοιχεία ενός αιτήματος όταν συνδέεται ο υπολογιστής σας. Κατεβαίνει μόνο η λίστα. Τίποτα δικό σας δεν ανεβαίνει μαζί της. Κάθε αρχείο έχει την υπογραφή του δημιουργού και η εφαρμογή την ελέγχει πριν χρησιμοποιήσει έστω μία λέξη. Μια διόρθωση που αλλάξατε ή σβήσατε μένει όπως την αφήσατε. Από τη σελίδα Λεξικό η λίστα αφαιρείται ξανά.'),
            ('h2', 'Πρακτικοί έλεγχοι'),
            ('ul', ['Επιβεβαιώστε την τοπική επιλογή στις Ρυθμίσεις πριν υπαγορεύσετε ευαίσθητο υλικό.', 'Κάντε μια μικρή δοκιμή χωρίς σύνδεση στον δικό σας υπολογιστή.', 'Ελέγξτε τι αποθηκεύεται στο Ιστορικό και τι αντιγράφετε σε άλλες υπηρεσίες.', 'Αν αναφέρετε πρόβλημα, διαβάστε τα διαγνωστικά πριν τα μοιραστείτε.']),
            ('h2', 'Κώδικας διαθέσιμος για έλεγχο'),
            ('p', 'Το FU Flow διατίθεται με άδεια MIT. Ο δημόσιος κώδικας περιλαμβάνει την επιλογή παρόχου, τις τοπικές και απομακρυσμένες μηχανές ομιλίας και τον έλεγχο ενημερώσεων. Η σελίδα περιγράφει τη λειτουργία της εφαρμογής. Δεν αποτελεί ανεξάρτητο έλεγχο ασφάλειας ή πιστοποίηση συμμόρφωσης.') ]},
}
